/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.GUI;
import View.DeepSpaceView;
import java.util.ArrayList;
import controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author shao
 */
public class GraphicMainView extends javax.swing.JFrame implements DeepSpaceView {
    
    private static GraphicMainView instance = null;
    private StationView stationView;
    private EnemyView enemyView;
    
    public static GraphicMainView getInstance() {
        if (instance == null) {
            instance = new GraphicMainView();
        }
        return instance;
    }

    /**
     * Creates new form GraphicMainView
     */
    private GraphicMainView() {
        initComponents();
        setTitle("GUI-Deepspace");
        
        stationView = new StationView();
        jpStarShip.add(stationView);
        
        enemyView = new EnemyView();
        jpEnemyStarShip.add(enemyView);
        
        repaint();
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                Controller.getInstance().finish(0);
            }
        });
    }
    
    @Override
    public void updateView() {
        enemyView.setEnemy(Controller.getInstance().getUIversion().getCurrentEnemy());
        stationView.setStation(Controller.getInstance().getUIversion().getCurrentStation());
    };
    
    @Override
    public void showView() {
        setVisible(true);
    };
    
    // Inputs
    @Override
    public ArrayList<String> readNamePlayers() {
        NamesCapture namesCaptures = new NamesCapture(this);
        return namesCaptures.getNames();
    };
    // Outputs
    @Override
    public boolean confirmExitMessage() {
        return (JOptionPane.showConfirmDialog(this, "¿Estás seguro/a de que deseas salir?", "Salida", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
    };
    @Override
    public void nextTurnNotAllowedMessage() {
        JOptionPane.showMessageDialog (this,"Siguiente turno no permitido.", "Deep Space 1.0", JOptionPane.INFORMATION_MESSAGE);
    };
    @Override
    public void lostCombatMessage() {
        JOptionPane.showMessageDialog (this,"Has PERDIDO el combate. \tCumple tu castigo.", "Deep Space 1.0", JOptionPane.INFORMATION_MESSAGE);
    };
    @Override
    public void escapeMessage() {
        JOptionPane.showMessageDialog (this,"Has logrado escapar. \tEres una Gallina Espacial.", "Deep Space 1.0", JOptionPane.INFORMATION_MESSAGE);;
    };
    @Override
    public void wonCombatMessage() {
        JOptionPane.showMessageDialog (this,"Has GANADO el combate. \tDisfruta de tu botín.", "Deep Space 1.0", JOptionPane.INFORMATION_MESSAGE);
    };
    @Override
    public void wonGameMessage() {
        JOptionPane.showMessageDialog (this,"\tHAS GANADO LA PARTIDA.", "Deep Space 1.0", JOptionPane.INFORMATION_MESSAGE);
    };
    @Override
    public void conversionMessage() {
        JOptionPane.showMessageDialog (this,"Te has CONVERTIDO.", "Deep Space 1.0", JOptionPane.INFORMATION_MESSAGE);
    };
    @Override
    public void noCombatMessage() {
        JOptionPane.showMessageDialog (this,"No puedes combatir en este momento.", "Deep Space 1.0", JOptionPane.INFORMATION_MESSAGE);
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpStarShip = new javax.swing.JPanel();
        jpEnemyStarShip = new javax.swing.JPanel();
        jbCombat = new javax.swing.JButton();
        jbNextTurn = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpStarShip.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpEnemyStarShip.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbCombat.setBackground(new java.awt.Color(204, 255, 204));
        jbCombat.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jbCombat.setText("COMBATIR");
        jbCombat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCombatMouseClicked(evt);
            }
        });

        jbNextTurn.setText("Siguente Turno");
        jbNextTurn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbNextTurnMouseClicked(evt);
            }
        });

        jbExit.setBackground(new java.awt.Color(255, 204, 204));
        jbExit.setText("Salir");
        jbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpStarShip, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpEnemyStarShip, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbNextTurn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbExit))
                        .addComponent(jbCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpStarShip, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpEnemyStarShip, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCombat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbNextTurn)
                            .addComponent(jbExit))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExitMouseClicked
        Controller.getInstance().finish(0);
    }//GEN-LAST:event_jbExitMouseClicked

    private void jbNextTurnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNextTurnMouseClicked
        Controller.getInstance().nextTurn();
        updateView();
    }//GEN-LAST:event_jbNextTurnMouseClicked

    private void jbCombatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCombatMouseClicked
        Controller.getInstance().combat();
        updateView();
    }//GEN-LAST:event_jbCombatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicMainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCombat;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbNextTurn;
    private javax.swing.JPanel jpEnemyStarShip;
    private javax.swing.JPanel jpStarShip;
    // End of variables declaration//GEN-END:variables
}
