/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.HangarToUI;
import deepspace.WeaponToUI;
import deepspace.ShieldToUI;
import java.util.ArrayList;
import java.awt.Component;
/**
 *
 * @author shao
 */
public class HangarView extends javax.swing.JPanel {
    
    private WeaponListView weaponListView;
    private ShieldBoosterListView shieldBoosterListView;

    /**
     * Creates new form HangarView
     */
    HangarView() {
        initComponents();
        
        weaponListView = new WeaponListView();
        jpWeapon.add(weaponListView);
        
        shieldBoosterListView = new ShieldBoosterListView();
        jpShield.add(shieldBoosterListView);
    }
    
    void setHangar(HangarToUI hangar) {
        clearView();
        
        jlCapacity.setText(Integer.toString(hangar.getMaxElements()));
        weaponListView.setWeapons(hangar.getWeapons());
        shieldBoosterListView.setShieldBoosters(hangar.getShieldBoosters());
        
        repaint();
        revalidate();
    }
    
    ArrayList<Integer> getSelectedWeapons() {
        return weaponListView.getSelectedWeapons();
    }
    
    ArrayList<Integer> getSelectedShields() {
        return shieldBoosterListView.getSelectedShields();
    }
    
    void clearView() {
        jlCapacity.setText("-1 (inválido)");
        weaponListView.clearView();
        shieldBoosterListView.clearView();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlCapacity = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpShield = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpWeapon = new javax.swing.JPanel();

        jLabel1.setText("Capacidad:");

        jlCapacity.setText("0");

        jScrollPane1.setViewportView(jpShield);

        jScrollPane2.setViewportView(jpWeapon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCapacity)
                .addContainerGap(70, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlCapacity;
    private javax.swing.JPanel jpShield;
    private javax.swing.JPanel jpWeapon;
    // End of variables declaration//GEN-END:variables
}
