/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.HangarToUI;
import deepspace.WeaponToUI;
import deepspace.ShieldToUI;
import java.util.ArrayList;
import java.awt.Component;
/**
 *
 * @author shao
 */
public class HangarView extends javax.swing.JPanel {

    /**
     * Creates new form HangarView
     */
    HangarView() {
        initComponents();
    }
    
    void setHangar(HangarToUI hangar) {
        clearView();
        
        jlCapacity.setText(Integer.toString(hangar.getMaxElements()));
        
        for (WeaponToUI weapon : hangar.getWeapons()) {
            WeaponView weaponView = new WeaponView();
            weaponView.setWeapon(weapon);
            jpWeapon.add(weaponView);
        }
        
        
        for (ShieldToUI shield : hangar.getShieldBoosters()) {
            ShieldBoosterView shieldBoosterView = new ShieldBoosterView();
            shieldBoosterView.setShield(shield);
            jpShield.add(shieldBoosterView);
        }
        
        repaint();
        revalidate();
    }
    
    ArrayList<Integer> getSelectedWeapons() {
        ArrayList<Integer> positions = new ArrayList<>();
        int i=0;
        
        for (Component c : jpWeapon.getComponents()) {
            if (((WeaponView) c).isSelected()) {
                positions.add(i);
            }
            ++i;
        }
        
        return positions;
    }
    
    ArrayList<Integer> getSelectedShields() {
        ArrayList<Integer> positions = new ArrayList<>();
        int i=0;
        
        for (Component c : jpShield.getComponents()) {
            if (((ShieldBoosterView) c).isSelected()) {
                positions.add(i);
            }
            ++i;
        }
        
        return positions;
    }
    
    void clearView() {
        jpWeapon.removeAll();
        jpShield.removeAll();
        jlCapacity.setText("-1 (inválido)");
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlCapacity = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpWeapon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpShield = new javax.swing.JPanel();

        jLabel1.setText("Capacidad:");

        jlCapacity.setText("0");

        jScrollPane1.setViewportView(jpWeapon);

        jScrollPane2.setViewportView(jpShield);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCapacity)
                .addContainerGap(48, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlCapacity;
    private javax.swing.JPanel jpShield;
    private javax.swing.JPanel jpWeapon;
    // End of variables declaration//GEN-END:variables
}
