/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.HangarToUI;
import deepspace.WeaponToUI;
import deepspace.ShieldToUI;
import java.util.ArrayList;
import java.awt.Component;
/**
 *
 * @author shao
 */
public class HangarView extends javax.swing.JPanel {
    
    private WeaponListView weaponListView;
    private ShieldBoosterListView shieldBoosterListView;

    /**
     * Creates new form HangarView
     */
    HangarView() {
        initComponents();
        
        weaponListView = new WeaponListView();
        jpWeapon.add(weaponListView);
        
        shieldBoosterListView = new ShieldBoosterListView();
        jpShield.add(shieldBoosterListView);
    }
    
    void setHangar(HangarToUI hangar) {
        clearView();
        
        jlCapacity.setText(Integer.toString(hangar.getMaxElements()));
        weaponListView.setWeapons(hangar.getWeapons());
        shieldBoosterListView.setShieldBoosters(hangar.getShieldBoosters());
        
        repaint();
        revalidate();
    }
    
    ArrayList<Integer> getSelectedWeapons() {
        return weaponListView.getSelectedWeapons();
    }
    
    ArrayList<Integer> getSelectedShields() {
        return shieldBoosterListView.getSelectedShields();
    }
    
    void clearView() {
        jlCapacity.setText("-1 (inválido)");
        weaponListView.clearView();
        shieldBoosterListView.clearView();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpShield = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlCapacity = new javax.swing.JLabel();
        jpWeapon = new javax.swing.JPanel();

        jpShield.setBorder(javax.swing.BorderFactory.createTitledBorder("Potenciadores de Defensa"));

        jLabel1.setText("Capacidad:");

        jlCapacity.setText("0");

        jpWeapon.setBorder(javax.swing.BorderFactory.createTitledBorder("Potenciadores de fuego"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpShield, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlCapacity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpShield, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jpWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlCapacity;
    private javax.swing.JPanel jpShield;
    private javax.swing.JPanel jpWeapon;
    // End of variables declaration//GEN-END:variables
}
