/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.ShieldToUI;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author shao
 */
public class ShieldBoosterListView extends javax.swing.JPanel {

    /**
     * Creates new form WeaponListView
     */
    public ShieldBoosterListView() {
        initComponents();
    }
    
    void setShieldBoosters(ArrayList<ShieldToUI> shields) {
        for (ShieldToUI s : shields) {
            ShieldBoosterView shieldBoosterView = new ShieldBoosterView();
            shieldBoosterView.setShield(s);
            jpShields.add(shieldBoosterView);
        }
        
        repaint();
        revalidate();
    }
    
    void clearView() {
        jpShields.removeAll();
    }
    
    ArrayList<Integer> getSelectedShields() {
        ArrayList<Integer> positions = new ArrayList<>();
        int i=0;
        
        for (Component c : jpShields.getComponents()) {
            if (((ShieldBoosterView) c).isSelected()) {
                positions.add(i);
            }
            ++i;
        }
        
        return positions;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpShields = new javax.swing.JPanel();

        jScrollPane1.setViewportView(jpShields);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpShields;
    // End of variables declaration//GEN-END:variables
}
