/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

/**
 *
 * @author shao
 */
public class StationView extends javax.swing.JPanel {
    
    private DamageView damageView;

    /**
     * Creates new form StationView
     */
    public StationView() {
        initComponents();
        
        repaint();
        revalidate();
        
        damageView = new DamageView();
        jpPendingDamage.add(damageView);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlDefense = new javax.swing.JLabel();
        jlPower = new javax.swing.JLabel();
        jlBoost = new javax.swing.JLabel();
        jlMedals = new javax.swing.JLabel();
        jpPendingDamage = new javax.swing.JPanel();
        jbDiscard = new javax.swing.JButton();
        jbEquip = new javax.swing.JButton();
        jbDiscardHangar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpWeapon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpShield = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jpHangar = new javax.swing.JPanel();

        jlName.setBackground(new java.awt.Color(255, 255, 255));
        jlName.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        jlName.setForeground(new java.awt.Color(0, 102, 0));
        jlName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlName.setText("Nombre de estación");

        jLabel2.setText("Potencia de Ataque:");

        jLabel3.setText("Nivel de Combustible:");

        jLabel4.setText("Potencia de Defensa: ");

        jLabel5.setText("Medallas:");

        jlDefense.setText("0,00");

        jlPower.setText("0,00");

        jlBoost.setText("0,00");

        jlMedals.setText("0");

        jpPendingDamage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Castigo Pendiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 17), new java.awt.Color(102, 0, 0))); // NOI18N
        jpPendingDamage.setForeground(new java.awt.Color(102, 0, 0));
        jpPendingDamage.setName(""); // NOI18N

        jbDiscard.setText("Descartar");
        jbDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDiscardActionPerformed(evt);
            }
        });

        jbEquip.setText("Equipar");
        jbEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEquipActionPerformed(evt);
            }
        });

        jbDiscardHangar.setText("Descartar Hangar");

        jpWeapon.setBorder(javax.swing.BorderFactory.createTitledBorder("Potenciadores de Fuego"));
        jScrollPane1.setViewportView(jpWeapon);

        jpShield.setBorder(javax.swing.BorderFactory.createTitledBorder("Potenciadores de Defensa"));
        jScrollPane2.setViewportView(jpShield);

        jpHangar.setBorder(javax.swing.BorderFactory.createTitledBorder("Hangar"));
        jScrollPane3.setViewportView(jpHangar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDefense, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBoost, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMedals, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlPower, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jpPendingDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbEquip)
                .addGap(18, 18, 18)
                .addComponent(jbDiscard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDiscardHangar)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPower)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDefense)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlBoost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jlMedals)))
                    .addComponent(jpPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDiscardHangar)
                    .addComponent(jbDiscard)
                    .addComponent(jbEquip))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEquipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEquipActionPerformed

    private void jbDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDiscardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbDiscardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbDiscard;
    private javax.swing.JButton jbDiscardHangar;
    private javax.swing.JButton jbEquip;
    private javax.swing.JLabel jlBoost;
    private javax.swing.JLabel jlDefense;
    private javax.swing.JLabel jlMedals;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlPower;
    private javax.swing.JPanel jpHangar;
    private javax.swing.JPanel jpPendingDamage;
    private javax.swing.JPanel jpShield;
    private javax.swing.JPanel jpWeapon;
    // End of variables declaration//GEN-END:variables
}
