/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.WeaponToUI;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author shao
 */
public class WeaponListView extends javax.swing.JPanel {

    /**
     * Creates new form WeaponListView
     */
    public WeaponListView() {
        initComponents();
    }
    
    void setWeapons(ArrayList<WeaponToUI> weapons) {
        for (WeaponToUI w : weapons) {
            WeaponView weaponView = new WeaponView();
            weaponView.setWeapon(w);
            jpWeapons.add(weaponView);
        }
        
        repaint();
        revalidate();
    }
    
    void clearView() {
        jpWeapons.removeAll();
    }
    
    ArrayList<Integer> getSelectedWeapons() {
        ArrayList<Integer> positions = new ArrayList<>();
        int i=0;
        
        for (Component c : jpWeapons.getComponents()) {
            if (((WeaponView) c).isSelected()) {
                positions.add(i);
            }
            ++i;
        }
        
        return positions;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpWeapons = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(155, 108));

        jScrollPane1.setViewportView(jpWeapons);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpWeapons;
    // End of variables declaration//GEN-END:variables
}
