/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.UI;
import View.DeepSpaceView;
import java.util.ArrayList;
import controller.Controller;

/**
 *
 * @author shao
 */
public class GraphicMainView extends javax.swing.JFrame implements DeepSpaceView {
    
    private static GraphicMainView instance = null;
    
    public static GraphicMainView getInstance() {
        if (instance == null) {
            instance = new GraphicMainView();
        }
        return instance;
    }

    /**
     * Creates new form GraphicMainView
     */
    private GraphicMainView() {
        initComponents();
        setTitle ("Título");
        repaint();
        setLocationRelativeTo(null);
        
        /*setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                Controller.getInstance().finish(0);
            }
        });*/
    }
    
    @Override
    public void updateView() {};
    
    @Override
    public void showView() {
        setVisible(true);
    };
    
    // Inputs
    @Override
    public ArrayList<String> readNamePlayers() {
        NamesCapture namesCaptures = new NamesCapture(this);
        return namesCaptures.getNames();
    };
    // Outputs
    @Override
    public boolean confirmExitMessage() {
        throw new UnsupportedOperationException();
    };
    @Override
    public void nextTurnNotAllowedMessage() {
        throw new UnsupportedOperationException();
    };
    @Override
    public void lostCombatMessage() {
        throw new UnsupportedOperationException();
    };
    @Override
    public void escapeMessage() {
        throw new UnsupportedOperationException();
    };
    @Override
    public void wonCombatMessage() {
        throw new UnsupportedOperationException();
    };
    @Override
    public void wonGameMessage() {
        throw new UnsupportedOperationException();
    };
    @Override
    public void conversionMessage() {
        throw new UnsupportedOperationException();
    };
    @Override
    public void noCombatMessage() {
        throw new UnsupportedOperationException();
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpStarShip = new javax.swing.JPanel();
        jpEnemyStarShip = new javax.swing.JPanel();
        jbCombat = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();
        jbNextTurn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpStarShip.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpEnemyStarShip.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbCombat.setBackground(new java.awt.Color(204, 255, 204));
        jbCombat.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jbCombat.setText("COMBATIR");

        jbExit.setText("Salir");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        jbNextTurn.setText("Siguente Turno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jpStarShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNextTurn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 455, Short.MAX_VALUE)
                        .addComponent(jbExit))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpEnemyStarShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpEnemyStarShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(jbCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbExit)
                            .addComponent(jbNextTurn)))
                    .addComponent(jpStarShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicMainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCombat;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbNextTurn;
    private javax.swing.JPanel jpEnemyStarShip;
    private javax.swing.JPanel jpStarShip;
    // End of variables declaration//GEN-END:variables
}
